/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Auction bid information */
export type AuctionBid = {
  /** Member who placed the bid */
  member: Address;
  /** Bid amount (interest rate in basis points) */
  amount: number;
  /** Timestamp when bid was placed */
  timestamp: bigint;
};

export type AuctionBidArgs = {
  /** Member who placed the bid */
  member: Address;
  /** Bid amount (interest rate in basis points) */
  amount: number;
  /** Timestamp when bid was placed */
  timestamp: number | bigint;
};

export function getAuctionBidEncoder(): FixedSizeEncoder<AuctionBidArgs> {
  return getStructEncoder([
    ['member', getAddressEncoder()],
    ['amount', getU16Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getAuctionBidDecoder(): FixedSizeDecoder<AuctionBid> {
  return getStructDecoder([
    ['member', getAddressDecoder()],
    ['amount', getU16Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getAuctionBidCodec(): FixedSizeCodec<
  AuctionBidArgs,
  AuctionBid
> {
  return combineCodec(getAuctionBidEncoder(), getAuctionBidDecoder());
}
