/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type AuctionStarted = {
  group: Address;
  auctionRound: Address;
  roundNumber: number;
  startTime: bigint;
  endTime: bigint;
  duration: bigint;
};

export type AuctionStartedArgs = {
  group: Address;
  auctionRound: Address;
  roundNumber: number;
  startTime: number | bigint;
  endTime: number | bigint;
  duration: number | bigint;
};

export function getAuctionStartedEncoder(): FixedSizeEncoder<AuctionStartedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['auctionRound', getAddressEncoder()],
    ['roundNumber', getU8Encoder()],
    ['startTime', getI64Encoder()],
    ['endTime', getI64Encoder()],
    ['duration', getU64Encoder()],
  ]);
}

export function getAuctionStartedDecoder(): FixedSizeDecoder<AuctionStarted> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['auctionRound', getAddressDecoder()],
    ['roundNumber', getU8Decoder()],
    ['startTime', getI64Decoder()],
    ['endTime', getI64Decoder()],
    ['duration', getU64Decoder()],
  ]);
}

export function getAuctionStartedCodec(): FixedSizeCodec<
  AuctionStartedArgs,
  AuctionStarted
> {
  return combineCodec(getAuctionStartedEncoder(), getAuctionStartedDecoder());
}
