/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Configuration for auction-based selection */
export type AuctionConfig = {
  /** Duration of auction phase in seconds */
  auctionDuration: bigint;
  /** Minimum bid increment in basis points */
  minBidIncrement: number;
  /** Maximum interest rate allowed (basis points) */
  maxInterestRate: number;
};

export type AuctionConfigArgs = {
  /** Duration of auction phase in seconds */
  auctionDuration: number | bigint;
  /** Minimum bid increment in basis points */
  minBidIncrement: number;
  /** Maximum interest rate allowed (basis points) */
  maxInterestRate: number;
};

export function getAuctionConfigEncoder(): FixedSizeEncoder<AuctionConfigArgs> {
  return getStructEncoder([
    ['auctionDuration', getU64Encoder()],
    ['minBidIncrement', getU16Encoder()],
    ['maxInterestRate', getU16Encoder()],
  ]);
}

export function getAuctionConfigDecoder(): FixedSizeDecoder<AuctionConfig> {
  return getStructDecoder([
    ['auctionDuration', getU64Decoder()],
    ['minBidIncrement', getU16Decoder()],
    ['maxInterestRate', getU16Decoder()],
  ]);
}

export function getAuctionConfigCodec(): FixedSizeCodec<
  AuctionConfigArgs,
  AuctionConfig
> {
  return combineCodec(getAuctionConfigEncoder(), getAuctionConfigDecoder());
}
