/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type BidPlaced = {
  group: Address;
  auctionRound: Address;
  roundNumber: number;
  member: Address;
  bidAmount: number;
  timestamp: bigint;
};

export type BidPlacedArgs = {
  group: Address;
  auctionRound: Address;
  roundNumber: number;
  member: Address;
  bidAmount: number;
  timestamp: number | bigint;
};

export function getBidPlacedEncoder(): FixedSizeEncoder<BidPlacedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['auctionRound', getAddressEncoder()],
    ['roundNumber', getU8Encoder()],
    ['member', getAddressEncoder()],
    ['bidAmount', getU16Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getBidPlacedDecoder(): FixedSizeDecoder<BidPlaced> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['auctionRound', getAddressDecoder()],
    ['roundNumber', getU8Decoder()],
    ['member', getAddressDecoder()],
    ['bidAmount', getU16Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getBidPlacedCodec(): FixedSizeCodec<BidPlacedArgs, BidPlaced> {
  return combineCodec(getBidPlacedEncoder(), getBidPlacedDecoder());
}
