/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type ContributionMade = {
  group: Address;
  round: Address;
  member: Address;
  amount: bigint;
  roundNumber: number;
  totalCollected: bigint;
};

export type ContributionMadeArgs = {
  group: Address;
  round: Address;
  member: Address;
  amount: number | bigint;
  roundNumber: number;
  totalCollected: number | bigint;
};

export function getContributionMadeEncoder(): FixedSizeEncoder<ContributionMadeArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['round', getAddressEncoder()],
    ['member', getAddressEncoder()],
    ['amount', getU64Encoder()],
    ['roundNumber', getU8Encoder()],
    ['totalCollected', getU64Encoder()],
  ]);
}

export function getContributionMadeDecoder(): FixedSizeDecoder<ContributionMade> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['round', getAddressDecoder()],
    ['member', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['roundNumber', getU8Decoder()],
    ['totalCollected', getU64Decoder()],
  ]);
}

export function getContributionMadeCodec(): FixedSizeCodec<
  ContributionMadeArgs,
  ContributionMade
> {
  return combineCodec(
    getContributionMadeEncoder(),
    getContributionMadeDecoder()
  );
}
