/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type EmergencyRefundInitiated = {
  group: Address;
  admin: Address;
  timestamp: bigint;
  reason: string;
};

export type EmergencyRefundInitiatedArgs = {
  group: Address;
  admin: Address;
  timestamp: number | bigint;
  reason: string;
};

export function getEmergencyRefundInitiatedEncoder(): Encoder<EmergencyRefundInitiatedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['admin', getAddressEncoder()],
    ['timestamp', getI64Encoder()],
    ['reason', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
  ]);
}

export function getEmergencyRefundInitiatedDecoder(): Decoder<EmergencyRefundInitiated> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['admin', getAddressDecoder()],
    ['timestamp', getI64Decoder()],
    ['reason', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getEmergencyRefundInitiatedCodec(): Codec<
  EmergencyRefundInitiatedArgs,
  EmergencyRefundInitiated
> {
  return combineCodec(
    getEmergencyRefundInitiatedEncoder(),
    getEmergencyRefundInitiatedDecoder()
  );
}
