/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type EmergencyRefundClaimed = {
  group: Address;
  member: Address;
  refundAmount: bigint;
  timestamp: bigint;
};

export type EmergencyRefundClaimedArgs = {
  group: Address;
  member: Address;
  refundAmount: number | bigint;
  timestamp: number | bigint;
};

export function getEmergencyRefundClaimedEncoder(): FixedSizeEncoder<EmergencyRefundClaimedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['member', getAddressEncoder()],
    ['refundAmount', getU64Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getEmergencyRefundClaimedDecoder(): FixedSizeDecoder<EmergencyRefundClaimed> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['member', getAddressDecoder()],
    ['refundAmount', getU64Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getEmergencyRefundClaimedCodec(): FixedSizeCodec<
  EmergencyRefundClaimedArgs,
  EmergencyRefundClaimed
> {
  return combineCodec(
    getEmergencyRefundClaimedEncoder(),
    getEmergencyRefundClaimedDecoder()
  );
}
