/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type FundsDistributed = {
  group: Address;
  round: Address;
  roundNumber: number;
  recipient: Address;
  amount: bigint;
  interestAmount: bigint;
  groupCompleted: boolean;
};

export type FundsDistributedArgs = {
  group: Address;
  round: Address;
  roundNumber: number;
  recipient: Address;
  amount: number | bigint;
  interestAmount: number | bigint;
  groupCompleted: boolean;
};

export function getFundsDistributedEncoder(): FixedSizeEncoder<FundsDistributedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['round', getAddressEncoder()],
    ['roundNumber', getU8Encoder()],
    ['recipient', getAddressEncoder()],
    ['amount', getU64Encoder()],
    ['interestAmount', getU64Encoder()],
    ['groupCompleted', getBooleanEncoder()],
  ]);
}

export function getFundsDistributedDecoder(): FixedSizeDecoder<FundsDistributed> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['round', getAddressDecoder()],
    ['roundNumber', getU8Decoder()],
    ['recipient', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['interestAmount', getU64Decoder()],
    ['groupCompleted', getBooleanDecoder()],
  ]);
}

export function getFundsDistributedCodec(): FixedSizeCodec<
  FundsDistributedArgs,
  FundsDistributed
> {
  return combineCodec(
    getFundsDistributedEncoder(),
    getFundsDistributedDecoder()
  );
}
