/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type GroupPaused = { group: Address; admin: Address; timestamp: bigint };

export type GroupPausedArgs = {
  group: Address;
  admin: Address;
  timestamp: number | bigint;
};

export function getGroupPausedEncoder(): FixedSizeEncoder<GroupPausedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['admin', getAddressEncoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getGroupPausedDecoder(): FixedSizeDecoder<GroupPaused> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['admin', getAddressDecoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getGroupPausedCodec(): FixedSizeCodec<
  GroupPausedArgs,
  GroupPaused
> {
  return combineCodec(getGroupPausedEncoder(), getGroupPausedDecoder());
}
