/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type GroupStarted = {
  group: Address;
  admin: Address;
  memberCount: number;
  firstRound: Address;
  targetAmount: bigint;
};

export type GroupStartedArgs = {
  group: Address;
  admin: Address;
  memberCount: number;
  firstRound: Address;
  targetAmount: number | bigint;
};

export function getGroupStartedEncoder(): FixedSizeEncoder<GroupStartedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['admin', getAddressEncoder()],
    ['memberCount', getU8Encoder()],
    ['firstRound', getAddressEncoder()],
    ['targetAmount', getU64Encoder()],
  ]);
}

export function getGroupStartedDecoder(): FixedSizeDecoder<GroupStarted> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['admin', getAddressDecoder()],
    ['memberCount', getU8Decoder()],
    ['firstRound', getAddressDecoder()],
    ['targetAmount', getU64Decoder()],
  ]);
}

export function getGroupStartedCodec(): FixedSizeCodec<
  GroupStartedArgs,
  GroupStarted
> {
  return combineCodec(getGroupStartedEncoder(), getGroupStartedDecoder());
}
