/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';
import {
  getCycleDurationDecoder,
  getCycleDurationEncoder,
  getSelectionMethodDecoder,
  getSelectionMethodEncoder,
  type CycleDuration,
  type CycleDurationArgs,
  type SelectionMethod,
  type SelectionMethodArgs,
} from '.';

export type GroupCreated = {
  group: Address;
  admin: Address;
  groupId: bigint;
  selectionMethod: SelectionMethod;
  maxMembers: number;
  contributionAmount: bigint;
  cycleDuration: CycleDuration;
};

export type GroupCreatedArgs = {
  group: Address;
  admin: Address;
  groupId: number | bigint;
  selectionMethod: SelectionMethodArgs;
  maxMembers: number;
  contributionAmount: number | bigint;
  cycleDuration: CycleDurationArgs;
};

export function getGroupCreatedEncoder(): Encoder<GroupCreatedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['admin', getAddressEncoder()],
    ['groupId', getU64Encoder()],
    ['selectionMethod', getSelectionMethodEncoder()],
    ['maxMembers', getU8Encoder()],
    ['contributionAmount', getU64Encoder()],
    ['cycleDuration', getCycleDurationEncoder()],
  ]);
}

export function getGroupCreatedDecoder(): Decoder<GroupCreated> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['admin', getAddressDecoder()],
    ['groupId', getU64Decoder()],
    ['selectionMethod', getSelectionMethodDecoder()],
    ['maxMembers', getU8Decoder()],
    ['contributionAmount', getU64Decoder()],
    ['cycleDuration', getCycleDurationDecoder()],
  ]);
}

export function getGroupCreatedCodec(): Codec<GroupCreatedArgs, GroupCreated> {
  return combineCodec(getGroupCreatedEncoder(), getGroupCreatedDecoder());
}
