/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Group status */
export enum GroupStatus {
  Forming,
  Active,
  Paused,
  Completed,
  Cancelled,
}

export type GroupStatusArgs = GroupStatus;

export function getGroupStatusEncoder(): FixedSizeEncoder<GroupStatusArgs> {
  return getEnumEncoder(GroupStatus);
}

export function getGroupStatusDecoder(): FixedSizeDecoder<GroupStatus> {
  return getEnumDecoder(GroupStatus);
}

export function getGroupStatusCodec(): FixedSizeCodec<
  GroupStatusArgs,
  GroupStatus
> {
  return combineCodec(getGroupStatusEncoder(), getGroupStatusDecoder());
}
