/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type InterestDistributed = {
  group: Address;
  round: Address;
  roundNumber: number;
  member: Address;
  interestAmount: bigint;
};

export type InterestDistributedArgs = {
  group: Address;
  round: Address;
  roundNumber: number;
  member: Address;
  interestAmount: number | bigint;
};

export function getInterestDistributedEncoder(): FixedSizeEncoder<InterestDistributedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['round', getAddressEncoder()],
    ['roundNumber', getU8Encoder()],
    ['member', getAddressEncoder()],
    ['interestAmount', getU64Encoder()],
  ]);
}

export function getInterestDistributedDecoder(): FixedSizeDecoder<InterestDistributed> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['round', getAddressDecoder()],
    ['roundNumber', getU8Decoder()],
    ['member', getAddressDecoder()],
    ['interestAmount', getU64Decoder()],
  ]);
}

export function getInterestDistributedCodec(): FixedSizeCodec<
  InterestDistributedArgs,
  InterestDistributed
> {
  return combineCodec(
    getInterestDistributedEncoder(),
    getInterestDistributedDecoder()
  );
}
