/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Member status within a group */
export enum MemberStatus {
  Active,
  Received,
  Left,
}

export type MemberStatusArgs = MemberStatus;

export function getMemberStatusEncoder(): FixedSizeEncoder<MemberStatusArgs> {
  return getEnumEncoder(MemberStatus);
}

export function getMemberStatusDecoder(): FixedSizeDecoder<MemberStatus> {
  return getEnumDecoder(MemberStatus);
}

export function getMemberStatusCodec(): FixedSizeCodec<
  MemberStatusArgs,
  MemberStatus
> {
  return combineCodec(getMemberStatusEncoder(), getMemberStatusDecoder());
}
