/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from '@solana/kit';

export type MemberJoined = {
  group: Address;
  member: Address;
  memberCount: number;
  fixedOrderPosition: Option<number>;
};

export type MemberJoinedArgs = {
  group: Address;
  member: Address;
  memberCount: number;
  fixedOrderPosition: OptionOrNullable<number>;
};

export function getMemberJoinedEncoder(): Encoder<MemberJoinedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['member', getAddressEncoder()],
    ['memberCount', getU8Encoder()],
    ['fixedOrderPosition', getOptionEncoder(getU8Encoder())],
  ]);
}

export function getMemberJoinedDecoder(): Decoder<MemberJoined> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['member', getAddressDecoder()],
    ['memberCount', getU8Decoder()],
    ['fixedOrderPosition', getOptionDecoder(getU8Decoder())],
  ]);
}

export function getMemberJoinedCodec(): Codec<MemberJoinedArgs, MemberJoined> {
  return combineCodec(getMemberJoinedEncoder(), getMemberJoinedDecoder());
}
