/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type MemberLeft = {
  group: Address;
  member: Address;
  remainingMembers: number;
};

export type MemberLeftArgs = MemberLeft;

export function getMemberLeftEncoder(): FixedSizeEncoder<MemberLeftArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['member', getAddressEncoder()],
    ['remainingMembers', getU8Encoder()],
  ]);
}

export function getMemberLeftDecoder(): FixedSizeDecoder<MemberLeft> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['member', getAddressDecoder()],
    ['remainingMembers', getU8Decoder()],
  ]);
}

export function getMemberLeftCodec(): FixedSizeCodec<
  MemberLeftArgs,
  MemberLeft
> {
  return combineCodec(getMemberLeftEncoder(), getMemberLeftDecoder());
}
