/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type PartialRefundProcessed = {
  group: Address;
  member: Address;
  refundAmount: bigint;
  timestamp: bigint;
};

export type PartialRefundProcessedArgs = {
  group: Address;
  member: Address;
  refundAmount: number | bigint;
  timestamp: number | bigint;
};

export function getPartialRefundProcessedEncoder(): FixedSizeEncoder<PartialRefundProcessedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['member', getAddressEncoder()],
    ['refundAmount', getU64Encoder()],
    ['timestamp', getI64Encoder()],
  ]);
}

export function getPartialRefundProcessedDecoder(): FixedSizeDecoder<PartialRefundProcessed> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['member', getAddressDecoder()],
    ['refundAmount', getU64Decoder()],
    ['timestamp', getI64Decoder()],
  ]);
}

export function getPartialRefundProcessedCodec(): FixedSizeCodec<
  PartialRefundProcessedArgs,
  PartialRefundProcessed
> {
  return combineCodec(
    getPartialRefundProcessedEncoder(),
    getPartialRefundProcessedDecoder()
  );
}
