/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Status of Switchboard randomness request */
export enum RandomnessStatus {
  NotRequested,
  Committed,
  Revealed,
  Failed,
}

export type RandomnessStatusArgs = RandomnessStatus;

export function getRandomnessStatusEncoder(): FixedSizeEncoder<RandomnessStatusArgs> {
  return getEnumEncoder(RandomnessStatus);
}

export function getRandomnessStatusDecoder(): FixedSizeDecoder<RandomnessStatus> {
  return getEnumDecoder(RandomnessStatus);
}

export function getRandomnessStatusCodec(): FixedSizeCodec<
  RandomnessStatusArgs,
  RandomnessStatus
> {
  return combineCodec(
    getRandomnessStatusEncoder(),
    getRandomnessStatusDecoder()
  );
}
