/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type RandomnessCommitted = {
  group: Address;
  round: Address;
  roundNumber: number;
  randomnessAccount: Address;
  committedSlot: bigint;
};

export type RandomnessCommittedArgs = {
  group: Address;
  round: Address;
  roundNumber: number;
  randomnessAccount: Address;
  committedSlot: number | bigint;
};

export function getRandomnessCommittedEncoder(): FixedSizeEncoder<RandomnessCommittedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['round', getAddressEncoder()],
    ['roundNumber', getU8Encoder()],
    ['randomnessAccount', getAddressEncoder()],
    ['committedSlot', getU64Encoder()],
  ]);
}

export function getRandomnessCommittedDecoder(): FixedSizeDecoder<RandomnessCommitted> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['round', getAddressDecoder()],
    ['roundNumber', getU8Decoder()],
    ['randomnessAccount', getAddressDecoder()],
    ['committedSlot', getU64Decoder()],
  ]);
}

export function getRandomnessCommittedCodec(): FixedSizeCodec<
  RandomnessCommittedArgs,
  RandomnessCommitted
> {
  return combineCodec(
    getRandomnessCommittedEncoder(),
    getRandomnessCommittedDecoder()
  );
}
