/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type RoundFinalized = {
  group: Address;
  round: Address;
  roundNumber: number;
  groupCompleted: boolean;
  totalCollected: bigint;
  totalDistributed: bigint;
};

export type RoundFinalizedArgs = {
  group: Address;
  round: Address;
  roundNumber: number;
  groupCompleted: boolean;
  totalCollected: number | bigint;
  totalDistributed: number | bigint;
};

export function getRoundFinalizedEncoder(): FixedSizeEncoder<RoundFinalizedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['round', getAddressEncoder()],
    ['roundNumber', getU8Encoder()],
    ['groupCompleted', getBooleanEncoder()],
    ['totalCollected', getU64Encoder()],
    ['totalDistributed', getU64Encoder()],
  ]);
}

export function getRoundFinalizedDecoder(): FixedSizeDecoder<RoundFinalized> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['round', getAddressDecoder()],
    ['roundNumber', getU8Decoder()],
    ['groupCompleted', getBooleanDecoder()],
    ['totalCollected', getU64Decoder()],
    ['totalDistributed', getU64Decoder()],
  ]);
}

export function getRoundFinalizedCodec(): FixedSizeCodec<
  RoundFinalizedArgs,
  RoundFinalized
> {
  return combineCodec(getRoundFinalizedEncoder(), getRoundFinalizedDecoder());
}
