/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Selection method for determining who receives funds each round */
export enum SelectionMethod {
  Auction,
  Random,
  FixedOrder,
}

export type SelectionMethodArgs = SelectionMethod;

export function getSelectionMethodEncoder(): FixedSizeEncoder<SelectionMethodArgs> {
  return getEnumEncoder(SelectionMethod);
}

export function getSelectionMethodDecoder(): FixedSizeDecoder<SelectionMethod> {
  return getEnumDecoder(SelectionMethod);
}

export function getSelectionMethodCodec(): FixedSizeCodec<
  SelectionMethodArgs,
  SelectionMethod
> {
  return combineCodec(getSelectionMethodEncoder(), getSelectionMethodDecoder());
}
