/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from '@solana/kit';
import {
  getSelectionMethodDecoder,
  getSelectionMethodEncoder,
  type SelectionMethod,
  type SelectionMethodArgs,
} from '.';

export type WinnerSelected = {
  group: Address;
  round: Address;
  roundNumber: number;
  selectedMember: Address;
  selectionMethod: SelectionMethod;
  interestRate: Option<number>;
};

export type WinnerSelectedArgs = {
  group: Address;
  round: Address;
  roundNumber: number;
  selectedMember: Address;
  selectionMethod: SelectionMethodArgs;
  interestRate: OptionOrNullable<number>;
};

export function getWinnerSelectedEncoder(): Encoder<WinnerSelectedArgs> {
  return getStructEncoder([
    ['group', getAddressEncoder()],
    ['round', getAddressEncoder()],
    ['roundNumber', getU8Encoder()],
    ['selectedMember', getAddressEncoder()],
    ['selectionMethod', getSelectionMethodEncoder()],
    ['interestRate', getOptionEncoder(getU16Encoder())],
  ]);
}

export function getWinnerSelectedDecoder(): Decoder<WinnerSelected> {
  return getStructDecoder([
    ['group', getAddressDecoder()],
    ['round', getAddressDecoder()],
    ['roundNumber', getU8Decoder()],
    ['selectedMember', getAddressDecoder()],
    ['selectionMethod', getSelectionMethodDecoder()],
    ['interestRate', getOptionDecoder(getU16Decoder())],
  ]);
}

export function getWinnerSelectedCodec(): Codec<
  WinnerSelectedArgs,
  WinnerSelected
> {
  return combineCodec(getWinnerSelectedEncoder(), getWinnerSelectedDecoder());
}
