/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SONTINE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const DISTRIBUTE_FUNDS_DISCRIMINATOR = new Uint8Array([
  124, 82, 187, 45, 224, 209, 31, 156,
]);

export function getDistributeFundsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DISTRIBUTE_FUNDS_DISCRIMINATOR
  );
}

export type DistributeFundsInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountGroup extends string | AccountMeta<string> = string,
  TAccountMemberAccount extends string | AccountMeta<string> = string,
  TAccountRound extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountMemberTokenAccount extends string | AccountMeta<string> = string,
  TAccountSelectedMember extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountRent extends
    | string
    | AccountMeta<string> = 'SysvarRent111111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGroup extends string
        ? WritableAccount<TAccountGroup>
        : TAccountGroup,
      TAccountMemberAccount extends string
        ? WritableAccount<TAccountMemberAccount>
        : TAccountMemberAccount,
      TAccountRound extends string
        ? WritableAccount<TAccountRound>
        : TAccountRound,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountMemberTokenAccount extends string
        ? WritableAccount<TAccountMemberTokenAccount>
        : TAccountMemberTokenAccount,
      TAccountSelectedMember extends string
        ? ReadonlyAccount<TAccountSelectedMember>
        : TAccountSelectedMember,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts,
    ]
  >;

export type DistributeFundsInstructionData = {
  discriminator: ReadonlyUint8Array;
  roundNumber: number;
};

export type DistributeFundsInstructionDataArgs = { roundNumber: number };

export function getDistributeFundsInstructionDataEncoder(): FixedSizeEncoder<DistributeFundsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['roundNumber', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: DISTRIBUTE_FUNDS_DISCRIMINATOR })
  );
}

export function getDistributeFundsInstructionDataDecoder(): FixedSizeDecoder<DistributeFundsInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['roundNumber', getU8Decoder()],
  ]);
}

export function getDistributeFundsInstructionDataCodec(): FixedSizeCodec<
  DistributeFundsInstructionDataArgs,
  DistributeFundsInstructionData
> {
  return combineCodec(
    getDistributeFundsInstructionDataEncoder(),
    getDistributeFundsInstructionDataDecoder()
  );
}

export type DistributeFundsAsyncInput<
  TAccountGroup extends string = string,
  TAccountMemberAccount extends string = string,
  TAccountRound extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountMemberTokenAccount extends string = string,
  TAccountSelectedMember extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
> = {
  group: Address<TAccountGroup>;
  memberAccount: Address<TAccountMemberAccount>;
  round?: Address<TAccountRound>;
  vault?: Address<TAccountVault>;
  mint: Address<TAccountMint>;
  memberTokenAccount: Address<TAccountMemberTokenAccount>;
  selectedMember: Address<TAccountSelectedMember>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
  roundNumber: DistributeFundsInstructionDataArgs['roundNumber'];
};

export async function getDistributeFundsInstructionAsync<
  TAccountGroup extends string,
  TAccountMemberAccount extends string,
  TAccountRound extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountMemberTokenAccount extends string,
  TAccountSelectedMember extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: DistributeFundsAsyncInput<
    TAccountGroup,
    TAccountMemberAccount,
    TAccountRound,
    TAccountVault,
    TAccountMint,
    TAccountMemberTokenAccount,
    TAccountSelectedMember,
    TAccountAuthority,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  DistributeFundsInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountMemberAccount,
    TAccountRound,
    TAccountVault,
    TAccountMint,
    TAccountMemberTokenAccount,
    TAccountSelectedMember,
    TAccountAuthority,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: true },
    memberAccount: { value: input.memberAccount ?? null, isWritable: true },
    round: { value: input.round ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    memberTokenAccount: {
      value: input.memberTokenAccount ?? null,
      isWritable: true,
    },
    selectedMember: { value: input.selectedMember ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.round.value) {
    accounts.round.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([114, 111, 117, 110, 100])),
        getAddressEncoder().encode(expectAddress(accounts.group.value)),
        getU8Encoder().encode(expectSome(args.roundNumber)),
      ],
    });
  }
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
        getAddressEncoder().encode(expectAddress(accounts.group.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.group),
      getAccountMeta(accounts.memberAccount),
      getAccountMeta(accounts.round),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.memberTokenAccount),
      getAccountMeta(accounts.selectedMember),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
    ],
    programAddress,
    data: getDistributeFundsInstructionDataEncoder().encode(
      args as DistributeFundsInstructionDataArgs
    ),
  } as DistributeFundsInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountMemberAccount,
    TAccountRound,
    TAccountVault,
    TAccountMint,
    TAccountMemberTokenAccount,
    TAccountSelectedMember,
    TAccountAuthority,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent
  >;

  return instruction;
}

export type DistributeFundsInput<
  TAccountGroup extends string = string,
  TAccountMemberAccount extends string = string,
  TAccountRound extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountMemberTokenAccount extends string = string,
  TAccountSelectedMember extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
> = {
  group: Address<TAccountGroup>;
  memberAccount: Address<TAccountMemberAccount>;
  round: Address<TAccountRound>;
  vault: Address<TAccountVault>;
  mint: Address<TAccountMint>;
  memberTokenAccount: Address<TAccountMemberTokenAccount>;
  selectedMember: Address<TAccountSelectedMember>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
  roundNumber: DistributeFundsInstructionDataArgs['roundNumber'];
};

export function getDistributeFundsInstruction<
  TAccountGroup extends string,
  TAccountMemberAccount extends string,
  TAccountRound extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountMemberTokenAccount extends string,
  TAccountSelectedMember extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: DistributeFundsInput<
    TAccountGroup,
    TAccountMemberAccount,
    TAccountRound,
    TAccountVault,
    TAccountMint,
    TAccountMemberTokenAccount,
    TAccountSelectedMember,
    TAccountAuthority,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): DistributeFundsInstruction<
  TProgramAddress,
  TAccountGroup,
  TAccountMemberAccount,
  TAccountRound,
  TAccountVault,
  TAccountMint,
  TAccountMemberTokenAccount,
  TAccountSelectedMember,
  TAccountAuthority,
  TAccountTokenProgram,
  TAccountSystemProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: true },
    memberAccount: { value: input.memberAccount ?? null, isWritable: true },
    round: { value: input.round ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    memberTokenAccount: {
      value: input.memberTokenAccount ?? null,
      isWritable: true,
    },
    selectedMember: { value: input.selectedMember ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.group),
      getAccountMeta(accounts.memberAccount),
      getAccountMeta(accounts.round),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.memberTokenAccount),
      getAccountMeta(accounts.selectedMember),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
    ],
    programAddress,
    data: getDistributeFundsInstructionDataEncoder().encode(
      args as DistributeFundsInstructionDataArgs
    ),
  } as DistributeFundsInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountMemberAccount,
    TAccountRound,
    TAccountVault,
    TAccountMint,
    TAccountMemberTokenAccount,
    TAccountSelectedMember,
    TAccountAuthority,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent
  >;

  return instruction;
}

export type ParsedDistributeFundsInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    group: TAccountMetas[0];
    memberAccount: TAccountMetas[1];
    round: TAccountMetas[2];
    vault: TAccountMetas[3];
    mint: TAccountMetas[4];
    memberTokenAccount: TAccountMetas[5];
    selectedMember: TAccountMetas[6];
    authority: TAccountMetas[7];
    tokenProgram: TAccountMetas[8];
    systemProgram: TAccountMetas[9];
    rent: TAccountMetas[10];
  };
  data: DistributeFundsInstructionData;
};

export function parseDistributeFundsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedDistributeFundsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      group: getNextAccount(),
      memberAccount: getNextAccount(),
      round: getNextAccount(),
      vault: getNextAccount(),
      mint: getNextAccount(),
      memberTokenAccount: getNextAccount(),
      selectedMember: getNextAccount(),
      authority: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getDistributeFundsInstructionDataDecoder().decode(instruction.data),
  };
}
