/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SONTINE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const EMERGENCY_PAUSE_DISCRIMINATOR = new Uint8Array([
  21, 143, 27, 142, 200, 181, 210, 255,
]);

export function getEmergencyPauseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EMERGENCY_PAUSE_DISCRIMINATOR
  );
}

export type EmergencyPauseInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountGroup extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGroup extends string
        ? WritableAccount<TAccountGroup>
        : TAccountGroup,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type EmergencyPauseInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type EmergencyPauseInstructionDataArgs = {};

export function getEmergencyPauseInstructionDataEncoder(): FixedSizeEncoder<EmergencyPauseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: EMERGENCY_PAUSE_DISCRIMINATOR })
  );
}

export function getEmergencyPauseInstructionDataDecoder(): FixedSizeDecoder<EmergencyPauseInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getEmergencyPauseInstructionDataCodec(): FixedSizeCodec<
  EmergencyPauseInstructionDataArgs,
  EmergencyPauseInstructionData
> {
  return combineCodec(
    getEmergencyPauseInstructionDataEncoder(),
    getEmergencyPauseInstructionDataDecoder()
  );
}

export type EmergencyPauseInput<
  TAccountGroup extends string = string,
  TAccountAdmin extends string = string,
> = {
  group: Address<TAccountGroup>;
  admin: TransactionSigner<TAccountAdmin>;
};

export function getEmergencyPauseInstruction<
  TAccountGroup extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: EmergencyPauseInput<TAccountGroup, TAccountAdmin>,
  config?: { programAddress?: TProgramAddress }
): EmergencyPauseInstruction<TProgramAddress, TAccountGroup, TAccountAdmin> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [getAccountMeta(accounts.group), getAccountMeta(accounts.admin)],
    programAddress,
    data: getEmergencyPauseInstructionDataEncoder().encode({}),
  } as EmergencyPauseInstruction<TProgramAddress, TAccountGroup, TAccountAdmin>;

  return instruction;
}

export type ParsedEmergencyPauseInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    group: TAccountMetas[0];
    admin: TAccountMetas[1];
  };
  data: EmergencyPauseInstructionData;
};

export function parseEmergencyPauseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedEmergencyPauseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      group: getNextAccount(),
      admin: getNextAccount(),
    },
    data: getEmergencyPauseInstructionDataDecoder().decode(instruction.data),
  };
}
