/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { SONTINE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const GET_AUCTION_STATISTICS_DISCRIMINATOR = new Uint8Array([
  135, 85, 235, 166, 72, 205, 128, 95,
]);

export function getGetAuctionStatisticsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_AUCTION_STATISTICS_DISCRIMINATOR
  );
}

export type GetAuctionStatisticsInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountAuctionRound extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuctionRound extends string
        ? ReadonlyAccount<TAccountAuctionRound>
        : TAccountAuctionRound,
      ...TRemainingAccounts,
    ]
  >;

export type GetAuctionStatisticsInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type GetAuctionStatisticsInstructionDataArgs = {};

export function getGetAuctionStatisticsInstructionDataEncoder(): FixedSizeEncoder<GetAuctionStatisticsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: GET_AUCTION_STATISTICS_DISCRIMINATOR,
    })
  );
}

export function getGetAuctionStatisticsInstructionDataDecoder(): FixedSizeDecoder<GetAuctionStatisticsInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getGetAuctionStatisticsInstructionDataCodec(): FixedSizeCodec<
  GetAuctionStatisticsInstructionDataArgs,
  GetAuctionStatisticsInstructionData
> {
  return combineCodec(
    getGetAuctionStatisticsInstructionDataEncoder(),
    getGetAuctionStatisticsInstructionDataDecoder()
  );
}

export type GetAuctionStatisticsInput<
  TAccountAuctionRound extends string = string,
> = {
  auctionRound: Address<TAccountAuctionRound>;
};

export function getGetAuctionStatisticsInstruction<
  TAccountAuctionRound extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: GetAuctionStatisticsInput<TAccountAuctionRound>,
  config?: { programAddress?: TProgramAddress }
): GetAuctionStatisticsInstruction<TProgramAddress, TAccountAuctionRound> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    auctionRound: { value: input.auctionRound ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [getAccountMeta(accounts.auctionRound)],
    programAddress,
    data: getGetAuctionStatisticsInstructionDataEncoder().encode({}),
  } as GetAuctionStatisticsInstruction<TProgramAddress, TAccountAuctionRound>;

  return instruction;
}

export type ParsedGetAuctionStatisticsInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    auctionRound: TAccountMetas[0];
  };
  data: GetAuctionStatisticsInstructionData;
};

export function parseGetAuctionStatisticsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedGetAuctionStatisticsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 1) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      auctionRound: getNextAccount(),
    },
    data: getGetAuctionStatisticsInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
