/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { SONTINE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const GET_GROUP_STATISTICS_DISCRIMINATOR = new Uint8Array([
  97, 215, 137, 171, 153, 47, 171, 76,
]);

export function getGetGroupStatisticsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_GROUP_STATISTICS_DISCRIMINATOR
  );
}

export type GetGroupStatisticsInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountGroup extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGroup extends string
        ? ReadonlyAccount<TAccountGroup>
        : TAccountGroup,
      ...TRemainingAccounts,
    ]
  >;

export type GetGroupStatisticsInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type GetGroupStatisticsInstructionDataArgs = {};

export function getGetGroupStatisticsInstructionDataEncoder(): FixedSizeEncoder<GetGroupStatisticsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: GET_GROUP_STATISTICS_DISCRIMINATOR })
  );
}

export function getGetGroupStatisticsInstructionDataDecoder(): FixedSizeDecoder<GetGroupStatisticsInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getGetGroupStatisticsInstructionDataCodec(): FixedSizeCodec<
  GetGroupStatisticsInstructionDataArgs,
  GetGroupStatisticsInstructionData
> {
  return combineCodec(
    getGetGroupStatisticsInstructionDataEncoder(),
    getGetGroupStatisticsInstructionDataDecoder()
  );
}

export type GetGroupStatisticsInput<TAccountGroup extends string = string> = {
  group: Address<TAccountGroup>;
};

export function getGetGroupStatisticsInstruction<
  TAccountGroup extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: GetGroupStatisticsInput<TAccountGroup>,
  config?: { programAddress?: TProgramAddress }
): GetGroupStatisticsInstruction<TProgramAddress, TAccountGroup> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [getAccountMeta(accounts.group)],
    programAddress,
    data: getGetGroupStatisticsInstructionDataEncoder().encode({}),
  } as GetGroupStatisticsInstruction<TProgramAddress, TAccountGroup>;

  return instruction;
}

export type ParsedGetGroupStatisticsInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    group: TAccountMetas[0];
  };
  data: GetGroupStatisticsInstructionData;
};

export function parseGetGroupStatisticsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedGetGroupStatisticsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 1) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      group: getNextAccount(),
    },
    data: getGetGroupStatisticsInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
