/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import { SONTINE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const GET_ROUND_STATISTICS_DISCRIMINATOR = new Uint8Array([
  81, 92, 171, 144, 144, 88, 192, 248,
]);

export function getGetRoundStatisticsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_ROUND_STATISTICS_DISCRIMINATOR
  );
}

export type GetRoundStatisticsInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountRound extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountRound extends string
        ? ReadonlyAccount<TAccountRound>
        : TAccountRound,
      ...TRemainingAccounts,
    ]
  >;

export type GetRoundStatisticsInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type GetRoundStatisticsInstructionDataArgs = {};

export function getGetRoundStatisticsInstructionDataEncoder(): FixedSizeEncoder<GetRoundStatisticsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: GET_ROUND_STATISTICS_DISCRIMINATOR })
  );
}

export function getGetRoundStatisticsInstructionDataDecoder(): FixedSizeDecoder<GetRoundStatisticsInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getGetRoundStatisticsInstructionDataCodec(): FixedSizeCodec<
  GetRoundStatisticsInstructionDataArgs,
  GetRoundStatisticsInstructionData
> {
  return combineCodec(
    getGetRoundStatisticsInstructionDataEncoder(),
    getGetRoundStatisticsInstructionDataDecoder()
  );
}

export type GetRoundStatisticsInput<TAccountRound extends string = string> = {
  round: Address<TAccountRound>;
};

export function getGetRoundStatisticsInstruction<
  TAccountRound extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: GetRoundStatisticsInput<TAccountRound>,
  config?: { programAddress?: TProgramAddress }
): GetRoundStatisticsInstruction<TProgramAddress, TAccountRound> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    round: { value: input.round ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [getAccountMeta(accounts.round)],
    programAddress,
    data: getGetRoundStatisticsInstructionDataEncoder().encode({}),
  } as GetRoundStatisticsInstruction<TProgramAddress, TAccountRound>;

  return instruction;
}

export type ParsedGetRoundStatisticsInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    round: TAccountMetas[0];
  };
  data: GetRoundStatisticsInstructionData;
};

export function parseGetRoundStatisticsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedGetRoundStatisticsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 1) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      round: getNextAccount(),
    },
    data: getGetRoundStatisticsInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
