/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SONTINE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const JOIN_GROUP_DISCRIMINATOR = new Uint8Array([
  121, 56, 199, 19, 250, 70, 44, 184,
]);

export function getJoinGroupDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(JOIN_GROUP_DISCRIMINATOR);
}

export type JoinGroupInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountGroup extends string | AccountMeta<string> = string,
  TAccountMemberAccount extends string | AccountMeta<string> = string,
  TAccountMember extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGroup extends string
        ? WritableAccount<TAccountGroup>
        : TAccountGroup,
      TAccountMemberAccount extends string
        ? WritableAccount<TAccountMemberAccount>
        : TAccountMemberAccount,
      TAccountMember extends string
        ? WritableSignerAccount<TAccountMember> &
            AccountSignerMeta<TAccountMember>
        : TAccountMember,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type JoinGroupInstructionData = { discriminator: ReadonlyUint8Array };

export type JoinGroupInstructionDataArgs = {};

export function getJoinGroupInstructionDataEncoder(): FixedSizeEncoder<JoinGroupInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: JOIN_GROUP_DISCRIMINATOR })
  );
}

export function getJoinGroupInstructionDataDecoder(): FixedSizeDecoder<JoinGroupInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getJoinGroupInstructionDataCodec(): FixedSizeCodec<
  JoinGroupInstructionDataArgs,
  JoinGroupInstructionData
> {
  return combineCodec(
    getJoinGroupInstructionDataEncoder(),
    getJoinGroupInstructionDataDecoder()
  );
}

export type JoinGroupAsyncInput<
  TAccountGroup extends string = string,
  TAccountMemberAccount extends string = string,
  TAccountMember extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  group: Address<TAccountGroup>;
  memberAccount?: Address<TAccountMemberAccount>;
  member: TransactionSigner<TAccountMember>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getJoinGroupInstructionAsync<
  TAccountGroup extends string,
  TAccountMemberAccount extends string,
  TAccountMember extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: JoinGroupAsyncInput<
    TAccountGroup,
    TAccountMemberAccount,
    TAccountMember,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  JoinGroupInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountMemberAccount,
    TAccountMember,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: true },
    memberAccount: { value: input.memberAccount ?? null, isWritable: true },
    member: { value: input.member ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.memberAccount.value) {
    accounts.memberAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([109, 101, 109, 98, 101, 114])),
        getAddressEncoder().encode(expectAddress(accounts.group.value)),
        getAddressEncoder().encode(expectAddress(accounts.member.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.group),
      getAccountMeta(accounts.memberAccount),
      getAccountMeta(accounts.member),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getJoinGroupInstructionDataEncoder().encode({}),
  } as JoinGroupInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountMemberAccount,
    TAccountMember,
    TAccountSystemProgram
  >;

  return instruction;
}

export type JoinGroupInput<
  TAccountGroup extends string = string,
  TAccountMemberAccount extends string = string,
  TAccountMember extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  group: Address<TAccountGroup>;
  memberAccount: Address<TAccountMemberAccount>;
  member: TransactionSigner<TAccountMember>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getJoinGroupInstruction<
  TAccountGroup extends string,
  TAccountMemberAccount extends string,
  TAccountMember extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: JoinGroupInput<
    TAccountGroup,
    TAccountMemberAccount,
    TAccountMember,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): JoinGroupInstruction<
  TProgramAddress,
  TAccountGroup,
  TAccountMemberAccount,
  TAccountMember,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: true },
    memberAccount: { value: input.memberAccount ?? null, isWritable: true },
    member: { value: input.member ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.group),
      getAccountMeta(accounts.memberAccount),
      getAccountMeta(accounts.member),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getJoinGroupInstructionDataEncoder().encode({}),
  } as JoinGroupInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountMemberAccount,
    TAccountMember,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedJoinGroupInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    group: TAccountMetas[0];
    memberAccount: TAccountMetas[1];
    member: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: JoinGroupInstructionData;
};

export function parseJoinGroupInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedJoinGroupInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      group: getNextAccount(),
      memberAccount: getNextAccount(),
      member: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getJoinGroupInstructionDataDecoder().decode(instruction.data),
  };
}
