/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SONTINE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const RESET_MEMBERS_FOR_NEW_ROUND_DISCRIMINATOR = new Uint8Array([
  144, 99, 246, 42, 240, 170, 182, 215,
]);

export function getResetMembersForNewRoundDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    RESET_MEMBERS_FOR_NEW_ROUND_DISCRIMINATOR
  );
}

export type ResetMembersForNewRoundInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountGroup extends string | AccountMeta<string> = string,
  TAccountMemberAccount extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGroup extends string
        ? ReadonlyAccount<TAccountGroup>
        : TAccountGroup,
      TAccountMemberAccount extends string
        ? WritableAccount<TAccountMemberAccount>
        : TAccountMemberAccount,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type ResetMembersForNewRoundInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ResetMembersForNewRoundInstructionDataArgs = {};

export function getResetMembersForNewRoundInstructionDataEncoder(): FixedSizeEncoder<ResetMembersForNewRoundInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: RESET_MEMBERS_FOR_NEW_ROUND_DISCRIMINATOR,
    })
  );
}

export function getResetMembersForNewRoundInstructionDataDecoder(): FixedSizeDecoder<ResetMembersForNewRoundInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getResetMembersForNewRoundInstructionDataCodec(): FixedSizeCodec<
  ResetMembersForNewRoundInstructionDataArgs,
  ResetMembersForNewRoundInstructionData
> {
  return combineCodec(
    getResetMembersForNewRoundInstructionDataEncoder(),
    getResetMembersForNewRoundInstructionDataDecoder()
  );
}

export type ResetMembersForNewRoundInput<
  TAccountGroup extends string = string,
  TAccountMemberAccount extends string = string,
  TAccountAdmin extends string = string,
> = {
  group: Address<TAccountGroup>;
  memberAccount: Address<TAccountMemberAccount>;
  admin: TransactionSigner<TAccountAdmin>;
};

export function getResetMembersForNewRoundInstruction<
  TAccountGroup extends string,
  TAccountMemberAccount extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: ResetMembersForNewRoundInput<
    TAccountGroup,
    TAccountMemberAccount,
    TAccountAdmin
  >,
  config?: { programAddress?: TProgramAddress }
): ResetMembersForNewRoundInstruction<
  TProgramAddress,
  TAccountGroup,
  TAccountMemberAccount,
  TAccountAdmin
> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: false },
    memberAccount: { value: input.memberAccount ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.group),
      getAccountMeta(accounts.memberAccount),
      getAccountMeta(accounts.admin),
    ],
    programAddress,
    data: getResetMembersForNewRoundInstructionDataEncoder().encode({}),
  } as ResetMembersForNewRoundInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountMemberAccount,
    TAccountAdmin
  >;

  return instruction;
}

export type ParsedResetMembersForNewRoundInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    group: TAccountMetas[0];
    memberAccount: TAccountMetas[1];
    admin: TAccountMetas[2];
  };
  data: ResetMembersForNewRoundInstructionData;
};

export function parseResetMembersForNewRoundInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedResetMembersForNewRoundInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      group: getNextAccount(),
      memberAccount: getNextAccount(),
      admin: getNextAccount(),
    },
    data: getResetMembersForNewRoundInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
