/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SONTINE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const SELECT_WINNER_DISCRIMINATOR = new Uint8Array([
  119, 66, 44, 236, 79, 158, 82, 51,
]);

export function getSelectWinnerDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SELECT_WINNER_DISCRIMINATOR
  );
}

export type SelectWinnerInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountGroup extends string | AccountMeta<string> = string,
  TAccountRound extends string | AccountMeta<string> = string,
  TAccountAuctionRound extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGroup extends string
        ? WritableAccount<TAccountGroup>
        : TAccountGroup,
      TAccountRound extends string
        ? WritableAccount<TAccountRound>
        : TAccountRound,
      TAccountAuctionRound extends string
        ? WritableAccount<TAccountAuctionRound>
        : TAccountAuctionRound,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type SelectWinnerInstructionData = {
  discriminator: ReadonlyUint8Array;
  roundNumber: number;
  eligibleMembers: Array<Address>;
};

export type SelectWinnerInstructionDataArgs = {
  roundNumber: number;
  eligibleMembers: Array<Address>;
};

export function getSelectWinnerInstructionDataEncoder(): Encoder<SelectWinnerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['roundNumber', getU8Encoder()],
      ['eligibleMembers', getArrayEncoder(getAddressEncoder())],
    ]),
    (value) => ({ ...value, discriminator: SELECT_WINNER_DISCRIMINATOR })
  );
}

export function getSelectWinnerInstructionDataDecoder(): Decoder<SelectWinnerInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['roundNumber', getU8Decoder()],
    ['eligibleMembers', getArrayDecoder(getAddressDecoder())],
  ]);
}

export function getSelectWinnerInstructionDataCodec(): Codec<
  SelectWinnerInstructionDataArgs,
  SelectWinnerInstructionData
> {
  return combineCodec(
    getSelectWinnerInstructionDataEncoder(),
    getSelectWinnerInstructionDataDecoder()
  );
}

export type SelectWinnerAsyncInput<
  TAccountGroup extends string = string,
  TAccountRound extends string = string,
  TAccountAuctionRound extends string = string,
  TAccountAuthority extends string = string,
> = {
  group: Address<TAccountGroup>;
  round?: Address<TAccountRound>;
  /** Optional auction round account for auction method */
  auctionRound?: Address<TAccountAuctionRound>;
  authority: TransactionSigner<TAccountAuthority>;
  roundNumber: SelectWinnerInstructionDataArgs['roundNumber'];
  eligibleMembers: SelectWinnerInstructionDataArgs['eligibleMembers'];
};

export async function getSelectWinnerInstructionAsync<
  TAccountGroup extends string,
  TAccountRound extends string,
  TAccountAuctionRound extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: SelectWinnerAsyncInput<
    TAccountGroup,
    TAccountRound,
    TAccountAuctionRound,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  SelectWinnerInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountRound,
    TAccountAuctionRound,
    TAccountAuthority
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: true },
    round: { value: input.round ?? null, isWritable: true },
    auctionRound: { value: input.auctionRound ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.round.value) {
    accounts.round.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([114, 111, 117, 110, 100])),
        getAddressEncoder().encode(expectAddress(accounts.group.value)),
        getU8Encoder().encode(expectSome(args.roundNumber)),
      ],
    });
  }
  if (!accounts.auctionRound.value) {
    accounts.auctionRound.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([97, 117, 99, 116, 105, 111, 110])
        ),
        getAddressEncoder().encode(expectAddress(accounts.group.value)),
        getU8Encoder().encode(expectSome(args.roundNumber)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.group),
      getAccountMeta(accounts.round),
      getAccountMeta(accounts.auctionRound),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getSelectWinnerInstructionDataEncoder().encode(
      args as SelectWinnerInstructionDataArgs
    ),
  } as SelectWinnerInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountRound,
    TAccountAuctionRound,
    TAccountAuthority
  >;

  return instruction;
}

export type SelectWinnerInput<
  TAccountGroup extends string = string,
  TAccountRound extends string = string,
  TAccountAuctionRound extends string = string,
  TAccountAuthority extends string = string,
> = {
  group: Address<TAccountGroup>;
  round: Address<TAccountRound>;
  /** Optional auction round account for auction method */
  auctionRound?: Address<TAccountAuctionRound>;
  authority: TransactionSigner<TAccountAuthority>;
  roundNumber: SelectWinnerInstructionDataArgs['roundNumber'];
  eligibleMembers: SelectWinnerInstructionDataArgs['eligibleMembers'];
};

export function getSelectWinnerInstruction<
  TAccountGroup extends string,
  TAccountRound extends string,
  TAccountAuctionRound extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: SelectWinnerInput<
    TAccountGroup,
    TAccountRound,
    TAccountAuctionRound,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): SelectWinnerInstruction<
  TProgramAddress,
  TAccountGroup,
  TAccountRound,
  TAccountAuctionRound,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: true },
    round: { value: input.round ?? null, isWritable: true },
    auctionRound: { value: input.auctionRound ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.group),
      getAccountMeta(accounts.round),
      getAccountMeta(accounts.auctionRound),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getSelectWinnerInstructionDataEncoder().encode(
      args as SelectWinnerInstructionDataArgs
    ),
  } as SelectWinnerInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountRound,
    TAccountAuctionRound,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedSelectWinnerInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    group: TAccountMetas[0];
    round: TAccountMetas[1];
    /** Optional auction round account for auction method */
    auctionRound?: TAccountMetas[2] | undefined;
    authority: TAccountMetas[3];
  };
  data: SelectWinnerInstructionData;
};

export function parseSelectWinnerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSelectWinnerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === SONTINE_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      group: getNextAccount(),
      round: getNextAccount(),
      auctionRound: getNextOptionalAccount(),
      authority: getNextAccount(),
    },
    data: getSelectWinnerInstructionDataDecoder().decode(instruction.data),
  };
}
