/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SONTINE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getAuctionConfigDecoder,
  getAuctionConfigEncoder,
  type AuctionConfig,
  type AuctionConfigArgs,
} from '../types';

export const UPDATE_GROUP_CONFIG_DISCRIMINATOR = new Uint8Array([
  237, 22, 68, 139, 99, 160, 215, 91,
]);

export function getUpdateGroupConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_GROUP_CONFIG_DISCRIMINATOR
  );
}

export type UpdateGroupConfigInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountGroup extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGroup extends string
        ? WritableAccount<TAccountGroup>
        : TAccountGroup,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateGroupConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  newMinMembersToStart: Option<number>;
  newAuctionConfig: Option<AuctionConfig>;
};

export type UpdateGroupConfigInstructionDataArgs = {
  newMinMembersToStart: OptionOrNullable<number>;
  newAuctionConfig: OptionOrNullable<AuctionConfigArgs>;
};

export function getUpdateGroupConfigInstructionDataEncoder(): Encoder<UpdateGroupConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['newMinMembersToStart', getOptionEncoder(getU8Encoder())],
      ['newAuctionConfig', getOptionEncoder(getAuctionConfigEncoder())],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_GROUP_CONFIG_DISCRIMINATOR })
  );
}

export function getUpdateGroupConfigInstructionDataDecoder(): Decoder<UpdateGroupConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['newMinMembersToStart', getOptionDecoder(getU8Decoder())],
    ['newAuctionConfig', getOptionDecoder(getAuctionConfigDecoder())],
  ]);
}

export function getUpdateGroupConfigInstructionDataCodec(): Codec<
  UpdateGroupConfigInstructionDataArgs,
  UpdateGroupConfigInstructionData
> {
  return combineCodec(
    getUpdateGroupConfigInstructionDataEncoder(),
    getUpdateGroupConfigInstructionDataDecoder()
  );
}

export type UpdateGroupConfigInput<
  TAccountGroup extends string = string,
  TAccountAdmin extends string = string,
> = {
  group: Address<TAccountGroup>;
  admin: TransactionSigner<TAccountAdmin>;
  newMinMembersToStart: UpdateGroupConfigInstructionDataArgs['newMinMembersToStart'];
  newAuctionConfig: UpdateGroupConfigInstructionDataArgs['newAuctionConfig'];
};

export function getUpdateGroupConfigInstruction<
  TAccountGroup extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof SONTINE_PROGRAM_ADDRESS,
>(
  input: UpdateGroupConfigInput<TAccountGroup, TAccountAdmin>,
  config?: { programAddress?: TProgramAddress }
): UpdateGroupConfigInstruction<TProgramAddress, TAccountGroup, TAccountAdmin> {
  // Program address.
  const programAddress = config?.programAddress ?? SONTINE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    group: { value: input.group ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [getAccountMeta(accounts.group), getAccountMeta(accounts.admin)],
    programAddress,
    data: getUpdateGroupConfigInstructionDataEncoder().encode(
      args as UpdateGroupConfigInstructionDataArgs
    ),
  } as UpdateGroupConfigInstruction<
    TProgramAddress,
    TAccountGroup,
    TAccountAdmin
  >;

  return instruction;
}

export type ParsedUpdateGroupConfigInstruction<
  TProgram extends string = typeof SONTINE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    group: TAccountMetas[0];
    admin: TAccountMetas[1];
  };
  data: UpdateGroupConfigInstructionData;
};

export function parseUpdateGroupConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateGroupConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      group: getNextAccount(),
      admin: getNextAccount(),
    },
    data: getUpdateGroupConfigInstructionDataDecoder().decode(instruction.data),
  };
}
